[workspace]
resolver = "2"

members = ["rs", "py"]
default-members = ["rs"]

[workspace.dependencies]
jpk_reader = { path = "rs" }
jpk_reader_rs = { path = "py" }

derive_more = "2.0"
tracing-subscriber = "0.3"
tracing = "0.1"
tracing-test = "0.2"
