[workspace]
resolver = "2"

members = ["jpk_reader"]
default-members = ["jpk_reader"]

[workspace.dependencies]
jpk_reader = { path = "..jpk_reader" }

derive_more = "2.0"
tracing-subscriber = "0.3"
tracing = "0.1"
tracing-test = "0.2"
